// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Performance", "CA1873:Avoid potentially expensive logging", Justification = "<Pending>", Scope = "member", Target = "~M:ModsBeforeFriday.Backend.Agent.MbfAgentClient.EnsureAgentAsync(System.String,System.IProgress{ModsBeforeFriday.Core.Models.AgentLogEntry},System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Performance", "CA1848:Use the LoggerMessage delegates", Justification = "<Pending>", Scope = "member", Target = "~M:ModsBeforeFriday.Backend.Agent.MbfAgentClient.SendAsync``1(System.String,ModsBeforeFriday.Core.Agent.AgentRequest,System.IProgress{ModsBeforeFriday.Core.Models.AgentLogEntry},System.Threading.CancellationToken)~System.Threading.Tasks.Task{``0}")]
[assembly: SuppressMessage("Performance", "CA1873:Avoid potentially expensive logging", Justification = "<Pending>", Scope = "member", Target = "~M:ModsBeforeFriday.Backend.Agent.MbfAgentClient.SendAsync``1(System.String,ModsBeforeFriday.Core.Agent.AgentRequest,System.IProgress{ModsBeforeFriday.Core.Models.AgentLogEntry},System.Threading.CancellationToken)~System.Threading.Tasks.Task{``0}")]
[assembly: SuppressMessage("Performance", "CA1848:Use the LoggerMessage delegates", Justification = "<Pending>", Scope = "member", Target = "~M:ModsBeforeFriday.Backend.Devices.AdbServerHealthService.EnsureAdbServerAsync(System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Performance", "CA1848:Use the LoggerMessage delegates", Justification = "<Pending>", Scope = "member", Target = "~M:ModsBeforeFriday.Backend.Devices.QuestService.CaptureLogcatAsync(ModsBeforeFriday.Core.Models.DeviceInfo,System.Threading.CancellationToken)~System.Threading.Tasks.Task{System.String}")]
[assembly: SuppressMessage("Performance", "CA1873:Avoid potentially expensive logging", Justification = "<Pending>", Scope = "member", Target = "~M:ModsBeforeFriday.Backend.Devices.QuestService.CaptureLogcatAsync(ModsBeforeFriday.Core.Models.DeviceInfo,System.Threading.CancellationToken)~System.Threading.Tasks.Task{System.String}")]
[assembly: SuppressMessage("Performance", "CA1848:Use the LoggerMessage delegates", Justification = "<Pending>", Scope = "member", Target = "~M:ModsBeforeFriday.Backend.Mods.ModCatalogService.LoadRepositoryAsync(System.String,System.Boolean,System.Threading.CancellationToken)~System.Threading.Tasks.Task{System.Collections.Generic.Dictionary{System.String,System.Collections.Generic.Dictionary{System.String,ModsBeforeFriday.Core.Models.ModCatalogMod}}}")]
[assembly: SuppressMessage("Performance", "CA1873:Avoid potentially expensive logging", Justification = "<Pending>", Scope = "member", Target = "~M:ModsBeforeFriday.Backend.Mods.ModCatalogService.LoadRepositoryAsync(System.String,System.Boolean,System.Threading.CancellationToken)~System.Threading.Tasks.Task{System.Collections.Generic.Dictionary{System.String,System.Collections.Generic.Dictionary{System.String,ModsBeforeFriday.Core.Models.ModCatalogMod}}}")]
